# Pulling Image

From mysql:5.6

# Copy Script file into Container 
Copy ./mysqlwithdata-Iteration1.sql /docker-entrypoint-initdb.d

# Settings the default user (root) password of mysql
Env MYSQL_ROOT_PASSWORD=wonderfulday
